### ISSUE TITLE
Connect the dots not triggering

### ISSUE THREAD

**Issue by p-sin** [halogenandtoast/ArkhamHorror#523] opened 2024-09-02 23:49 UTC
https://arkhamhorror.app/#/games/0d2bbc35-20a7-4757-8007-e11b838acdb2

Getting last two clues from location using 'shed a light'. 'Crack the case' has triggered, but 'Connect the dots' has not

**Comment by halogenandtoast** [comment] 2024-09-12 03:34
Duplicate of #553 

Also this game is deleted so can't do much else here.

**Closed by halogenandtoast** 2024-09-12 03:34 UTC
Labels: bug
