### ISSUE TITLE
Getting 1 damage per enemy phase like if I were still engaged to an enemy

### ISSUE THREAD

**Issue by stefano-bragaglia** [halogenandtoast/ArkhamHorror#86] opened 2022-06-22 11:07 UTC
* I've dealt with `Victoria Deveraux`, one of the cultists in Midnight Masks (the one dealing 1 damage) using the action on her text.
* Ever since I play a card or pass an enemy phase, I get a damage.

I tried to fix the status of the game by using "Toggle Debug" but the "-" button for Damage was missing and the buttons were all messed up.
<img width="664" alt="Screenshot 2022-06-22 at 11 20 00" src="https://user-images.githubusercontent.com/4399978/175014415-6188a531-b2cf-49f7-a3b8-320c44b0f36e.png">
[arkham-debug.json.gz](https://github.com/halogenandtoast/ArkhamHorror/files/8956992/arkham-debug.json.gz)

**Comment by halogenandtoast** [comment] 2022-06-22 13:18
@stefano-bragaglia the bottons for each token are to the right of of the token:

<img width="93" alt="Screen Shot 2022-06-22 at 8 15 53" src="https://user-images.githubusercontent.com/201288/175038186-b12f71ef-9265-423b-88dd-04c6c6e315a4.png">

Notes for self:

This issue is tied to a previous fix for Ghoul Priest. The timing of defeated/added to victory was messing with the resolution of "What Have You Done?". Previously, `AddToVictory` would remove the enemy from the game state, but then "What Have You Done?" could no longer tell if the enemy defeated was the ghoul priest. The previous fix moved the logic into a step of `EnemyDefeated`, but with "Victoria Devereaux" that card is added directly to the victory display.

A solution needs to take both situations into account, ideally we have two scenarios that look like this:

### ghoul priest scenario
When AddedToVictory, After AddedToVictory, When Defeated, After Defeated, Remove Enemy.

### victoria devereaux scenario
When AddedToVictory, After AddedToVictory, RemoveEnemy

The issue is that in both cases added to victory AND defeated will want to remove the enemy, if defeated checks if enemy is victory then we run into the case that the removal will happen before the defeated windows causing issues, If we run the defeated windows before added to victory, then ghoul priest will never end up in the victory display and you won't get the XP.

**Comment by halogenandtoast** [comment] 2022-06-22 13:21
The easiest solution will be to split add to victory into 2 messages. Update AddToVictory to remove the enemy, but add a new DefeatedAddToVictory that synchronizes the windows correctly.

**Comment by halogenandtoast** [comment] 2022-06-22 14:28
Fixed in db0659845851dc066bc83e379516734cc6befc07

**Closed by halogenandtoast** 2022-06-22 14:28 UTC
Labels: bug
