### ISSUE TITLE
Quick Thinking Extra Action

### ISSUE THREAD

**Issue by AUscarface79** [halogenandtoast/ArkhamHorror#473] opened 2024-08-30 11:56 UTC
**Provide a Game ID**
dccf72e5-a8b9-4c8d-90d6-3f1141a7910e

**Describe the bug**
Commiting "Quick Thinking" to another investigator's test and succeeding gives the immediate action to the investigator who initiated the test and not to the one who commited the card.

**Comment by mniksa3** [comment] 2024-08-31 03:45
this is a duplicate of
https://github.com/halogenandtoast/ArkhamHorror/issues/462

**Closed** 2024-09-06 23:54 UTC
Labels: bug, Fix Incoming
