### ISSUE TITLE
I can't load a debug export

### ISSUE THREAD

**Issue by HyperboreanSorcerer** [halogenandtoast/ArkhamHorror#321] opened 2024-08-19 19:21 UTC
So, I'm trying to load a debug export, but nothing seems to happen.

**Comment by HyperboreanSorcerer** [comment] 2024-08-19 19:25
Ok, I managed to do it with a different export this time.

**Comment by halogenandtoast** [comment] 2024-08-20 01:02
Ah the debug exports are mainly for me to test with locally. Usually the file size is too big to send to the server. 

I should probably disable the UI on production, but out of curiosity what did you want to do with the export?

**Comment by halogenandtoast** [comment] 2024-08-21 05:23
Going to close this since it's not a bug, but as mentioned above I'd be curious to know the usecase because I might be able to make a more reasonable export for other use cases.

**Closed by halogenandtoast** 2024-08-21 05:23 UTC
Labels: bug
