### ISSUE TITLE
Jazz Mulligan doesn't appear on the map

### ISSUE THREAD

**Issue by stefano-bragaglia** [halogenandtoast/ArkhamHorror#107] opened 2022-07-14 22:46 UTC
In Extracurricular Activity, I eventually discard Jazz Mulligan and the Forced action on the current Act triggers, activating Jazz Mulligan's Revelation effect which puts it into play at my location.

The cards should be added to the Science Building, however it doesn't show up.
In other words, there is no trigger to press to Parley and gain control of Jazz.
Without him in play, the scenario cannot be won...

The status of the game is below.
[arkham-debug.json.gz](https://github.com/halogenandtoast/ArkhamHorror/files/9115993/arkham-debug.json.gz)

**Comment by halogenandtoast** [comment] 2022-07-14 23:16
Should be fixed in 98af895416290e3d03ddd7e11ce824e6c0b0ead1

**Comment by stefano-bragaglia** [comment] 2022-07-15 10:29
It is indeed fixed, thanks!

A followup, still related to Jazz Mulligan.

I'm trying to Parley to gain control of him. I'm playing as Wendy Adams and I have Fine Clothes in play: my ability score (Book) is 3, the difficulty of the Parley is 3, but Fine Clothes should reduce the difficulty by 2 (to 1). 

I started the test, and draw a -1 Chaos token. I should have passed it (3 +0 -1 vs. 1), but Fine Clothes reduction is not counted and it turns out I fail by -1 (3 +0 -1 vs. 3).

<img width="2032" alt="image" src="https://user-images.githubusercontent.com/4399978/179205775-532edba3-98c0-47b9-b40b-49749370338f.png">

[arkham-debug.json.gz](https://github.com/halogenandtoast/ArkhamHorror/files/9120068/arkham-debug.json.gz)

**Comment by halogenandtoast** [comment] 2022-07-15 12:49
Fixed in a62a26b695de07e88314a5c35739336f6d0d7177

**Comment by halogenandtoast** [comment] 2022-07-15 12:49
You will need to back up all the way before you initiated the skill test.

**Comment by stefano-bragaglia** [comment] 2022-07-15 18:44
I updated (dc down/pull/dc up/hard reload) and went back all the way before initiating the skill test. 

I then started the skill test again, but it played exactly in the same way as before. 
Going back and forward worked with Jazz the first time, but not with Fine Clothes.

Can I do anything else to make it work?

**Comment by stefano-bragaglia** [comment] 2022-07-15 18:48
By the way, @halogenandtoast, apologies if I slow your work down with these little issues. Didn't mean to take your attention away from the new cards!

Let me know if you'd rather me to stop reporting things until you've finished with the cards you're adding, or if it's fine to continue opening tickets.

**Comment by stefano-bragaglia** [comment] 2022-07-15 22:06
I tried to pull the latest commit, but I was already in par.
When I started the server, however, I managed to get past the Parley test.
Possibly it did work because I undid the last few steps up to before the parley before turning off and on again the server... I don't know.

Anyway, its ability "While you control "Jazz" Mulligan, you ignore the text on each unrevealed Miskatonic location." doesn't trigger, in fact I cannot enter into the Alchemy Labs where The Experiment is waiting for me...

**Comment by halogenandtoast** [comment] 2022-07-15 22:59
oof the jazz ability is going to be difficult to fix, I'll have to think on this.

**Comment by halogenandtoast** [comment] 2022-07-16 03:52
Okay fixed that, one thing I've noticed is this solution has some performance penalties that I will need to figure out eventually, but not now it works as intended.

**Comment by halogenandtoast** [comment] 2022-07-16 14:26
I've recently pushed up a bunch of dunwich related fixes (at least for the first two scenarios), so I would suggest updating when you get the chance.

**Comment by halogenandtoast** [comment] 2022-07-16 17:26
If more things go wrong from here, can you open new issues specific to the card or ruling, it will make it a little easier to track.

**Closed by halogenandtoast** 2022-07-16 17:26 UTC
